### ISSUE TITLE
How can I get ROUGE score

### ISSUE THREAD

**Issue by demdecuong** [domyounglee/Transformer-Summarization#2]
Thank you for this great repo,

Could you give me some instructions to get ROUGE score

**Comment by domyounglee** [comment]
I got it from https://medium.com/@prabha88978/installation-working-process-of-rouge-1-5-5-6c0dfdca49e8
After you installed it from the repository you should erase the database in ROUGE-1.5.5/data 
and execute the command line.
./WordNet-2.0-Exceptions/buildExeptionDB.pl ./WordNet-2.0-Exceptions ./smart_common_words.txt ./WordNet-2.0.exc.db
